### ISSUE TITLE
拱墅区部分学区

### ISSUE THREAD

**Issue by owenlyn0123** [xieguanglei/schools-map#2]
[学区数据-杭州市拱墅区.txt](https://github.com/xieguanglei/schools-map/files/3817515/-.txt)

**Comment by xieguanglei** [comment]
Awesome, I've never expected someone would contribute to this project. Thank you a lot, I'll check the data and merge to the project soon.

**Comment by owenlyn0123** [comment]
You 're welcome. Actually, I have written a series of articles about the
introduction of primary schools in Hangzhou. In detail, for the School
District part, I've referred your project, which helps me a lot. Thank you
as well!

Xie Guanglei <notifications@github.com> 于2019年11月8日周五 上午9:37写道：

**Comment by xieguanglei** [comment]
data merged in the recent commit 7628137877d17c0b1d9949ec810921c8ecf15af9
